name: My First Action

on:
  push:
    branches: [main]

jobs:
  my-job:
    runs-on: [ubuntu-latest, macos-latest, windows-latest]
    strategy:
      matrix:
        os: [ubuntu, macos, windows]

    steps:
      - uses: actions/checkout@v3
      - name: Run OS-specific commands
        run: |
          if [[ "${{ runner.os }}" == "Linux" ]]; then
            # Commands for Linux
            echo "This is Linux"
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            # Commands for macOS
            echo "This is macOS"
          elif [[ "${{ runner.os }}" == "Windows" ]]; then
            # Commands for Windows
            echo "This is Windows"
          fi
          echo "Test done!"
